name: Scrape
on:
  push:
    branches: [main]
  schedule:
    - cron: '33 12,14,17,22 * * *'

jobs:
  scraper-dengue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: execute my python script 
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-autoinstaller
          pip install -r requirements.txt
          python test.py

      - name: commit my files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git commit --allow-empty -m "update data daily dengue"
      - name: push my changes to github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch : main

