name: Scrape
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 13,15,17,22 * * *'

jobs:
  scraper-dengue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: execute my python script 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python test.py
      - name: commit my files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git commit --allow-empty -m "update data daily dengue"


